### ISSUE TITLE
Application fails to start

### ISSUE THREAD

**Issue by Qazerowl** [xmikos/hangupsbot#1]
I've cloned the repo, ran setup.py install, and pip3 belives all the dependencies are satisfied. hangupsbot returns:

```
  Traceback (most recent call last):
File "/usr/bin/hangupsbot", line 4, in <module>
  hangupsbot.main()
File "/usr/lib/python3.4/site-packages/hangupsbot/hangupsbot.py", line 284, in main
  bot = HangupsBot(args.cookies, args.config)
File "/usr/lib/python3.4/site-packages/hangupsbot/hangupsbot.py", line 51, in __init__
  self.config = hangupsbot.config.Config(config_path)
File "/usr/lib/python3.4/site-packages/hangupsbot/config.py", line 11, in __init__
  self.load()
File "/usr/lib/python3.4/site-packages/hangupsbot/config.py", line 16, in load
  self.config = json.load(open(self.filename))
File "/usr/lib/python3.4/json/__init__.py", line 268, in load
  parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
  return _default_decoder.decode(s)
File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
  obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
  raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 5 column 3 (char 100)
```

**Comment by wardellbagby** [comment]
Sounds like your config json file is missing something somewhere. Post it here with any user ids and conversation ids removed.

**Comment by zyrorl** [comment]
@wardellchandler it actually is due to the fact that the config.json is not valid JSON in the hangupsbot package... if you fix it with below it'll work fine..

``` javascript

{
  "admins": ["USER1_ID", "USER2_ID"],
  "autoreplies": [
    [["hi", "hello"], "Hello world!"]
  ],
  "autoreplies_enabled": true,
  "commands_admin": ["rename", "leave", "easteregg", "user", "users", "hangouts", "reload", "quit", "config"],
  "commands_enabled": true,
  "forwarding_enabled": true,
  "conversations": {
    "CONV1_ID": {
      "forward_to": [
        "CONV2_ID"
      ]
    },
    "CONV2_ID": {
      "autoreplies_enabled": false,
      "commands_enabled": false,
      "forwarding_enabled": false,
      "forward_to": [
        "CONV1_ID"
      ]
    }
  }
}
```

**Comment by xmikos** [comment]
@Qazerowl I have fixed config.json in latest commit, thanks for info...
