### ISSUE TITLE
Invalid syntax on line 115

### ISSUE THREAD

**Issue by murfjr** [xmikos/hangupsbot#5]
pi@raspberrypi ~/hangupsbot $ python3 hangupsbot
Traceback (most recent call last):
  File "/usr/lib/python3.2/runpy.py", line 143, in _run_module_as_main
    mod_name, loader, code, fname = _get_main_module_details()
  File "/usr/lib/python3.2/runpy.py", line 186, in _get_main_module_details
    return _get_module_details(main_name)
  File "/usr/lib/python3.2/runpy.py", line 115, in _get_module_details
    code = loader.get_code(mod_name)
  File "/usr/lib/python3.2/pkgutil.py", line 281, in get_code
    self.code = compile(source, self.filename, 'exec')
  File "/home/pi/hangupsbot/hangupsbot/__main__.py", line 115
    res = yield from http_utils.fetch('get', link)
                   ^
SyntaxError: invalid syntax

is there any way to fix this? I'm using python3.4.3.

**Comment by xmikos** [comment]
It seems that you are _not_ using Python 3.4, see that `python3.2` in your path. You need at least Python 3.3 (+ external backported _asyncio_ module) or Python 3.4 for HangupsBot (older version didn't support `yield from` syntax).
